### PR TITLE
CSV import for IPT2019

### PR DESCRIPTION
**Pull request by nickkolok**
Only the necessary minimum of fields is imported, see #117.
Teams are created automatically during the import process.

### CODE REVIEW

**Comment by nickkolok** [comment]
Team Leaders are imported only as jurors (if they can judge), not as participants. Is this OK ?

**Comment by vbonvin** [comment]
Commits are fine, you can pull.

On a side note, I personally don't think csv import should become a thing in the future. It seems more appropriate to me to directly enter the participant's info at the time of registration into the database - which hasn't been done this year for lack of manpower, but has been used in the 2 (3?) previous years and worked quite well.

**Comment by nickkolok** [comment]
> On a side note, I personally don't think csv import should become a thing in the future.

I still disagree with you. If you want, we can proceed the discussion in #117.

**Comment by nickkolok** [comment]
Sorry for force-push... There was a minor conflict with semifinals branch (both branches edited the end of `views.py`), so a careful rebase seemed to be the best solution, much better than merging.

**Pull request merged**
